#------------------------------------------------------------------------------------
# HEY! This file is code from Crop & Kettle by Creature Comforts!
# We have been given permission to utilize it for use at smithed summit by MaybeJake.
# We do NOT claim any legal right or creative license to this file.
#------------------------------------------------------------------------------------

execute if score $mixing_bowl_item_count spiced.dummy matches 2 \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"wheat"}}}}}] \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"water_bottle"}}}}}] \
        if function spiced:mixing_bowl/mix/lock \
        run return run data modify entity @s item.components."minecraft:custom_data".spiced.mix_callback set value "spiced:recipes/mixing_bowl/dough"

execute if score $mixing_bowl_item_count spiced.dummy matches 4 \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"salt"}}}}}] \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"flour"}}}}}] \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"butter"}}}}}] \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"egg"}}}}}] \
        if function spiced:mixing_bowl/mix/lock \
        run return run data modify entity @s item.components."minecraft:custom_data".spiced.mix_callback set value "spiced:recipes/mixing_bowl/pastry_dough"

execute if score $mixing_bowl_item_count spiced.dummy matches 4 \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"chicken"}}}}}] \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"porkchop"}}}}}] \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"diced_bread"}}}}}] \
        if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"huntsman_pie_incomplete_1"}}}}}] \
        if function spiced:mixing_bowl/mix/lock \
        run return run data modify entity @s item.components."minecraft:custom_data".spiced.mix_callback set value "spiced:recipes/mixing_bowl/huntsman_pie_incomplete_2"

# code below is generated by beet
execute if score $mixing_bowl_item_count spiced.dummy matches 1 if function spiced:mixing_bowl/mix/generic/milk if score $milk_count spiced.dummy matches 1.. if function spiced:mixing_bowl/mix/lock run return run data modify entity @s item.components.'minecraft:custom_data'.spiced.mix_callback set value 'spiced:recipes/mixing_bowl/butter'
execute if score $mixing_bowl_item_count spiced.dummy matches 2 if data storage spiced:temp mixing_bowl.Items[{id:'minecraft:glass_bottle'}] if data storage spiced:temp mixing_bowl.Items[{components:{"minecraft:custom_data":{"spiced":{"ingredient":{"type":"sunflower"}}}}}] if function spiced:mixing_bowl/mix/lock run return run data modify entity @s item.components.'minecraft:custom_data'.spiced.mix_callback set value 'spiced:recipes/mixing_bowl/cooking_oil'