execute if score $mixing_bowl_item_count spiced.dummy matches 2 \
        if data storage spiced:temp mixing_bowl.Items[{id:"minecraft:wheat"}] \
        if function spiced:mixing_bowl/mix/generic/water if score $water_count spiced.dummy matches 1 \
        if function spiced:mixing_bowl/mix/lock \
        run return run data modify entity @s item.components."minecraft:custom_data".spiced.mix_callback set value "spiced:recipes/mixing_bowl/dough"

execute if score $mixing_bowl_item_count spiced.dummy matches 2 \
        if data storage spiced:temp mixing_bowl.Items[{id:"minecraft:wheat"}] \
        if function spiced:mixing_bowl/mix/generic/egg if score $egg_count spiced.dummy matches 1 \
        if function spiced:mixing_bowl/mix/lock \
        run return run data modify entity @s item.components."minecraft:custom_data".spiced.mix_callback set value "spiced:recipes/mixing_bowl/egg_dough"

# code below is generated by beet


execute if score $mixing_bowl_item_count spiced.dummy matches 1 if function spiced:mixing_bowl/mix/generic/milk if score $milk_count spiced.dummy matches 1.. if function spiced:mixing_bowl/mix/lock run return run data modify entity @s item.components.'minecraft:custom_data'.spiced.mix_callback set value 'spiced:recipes/mixing_bowl/butter'
execute if score $mixing_bowl_item_count spiced.dummy matches 2 if data storage spiced:temp mixing_bowl.Items[{id:'minecraft:glass_bottle'}] if data storage spiced:temp mixing_bowl.Items[{id:'minecraft:sunflower'}] if function spiced:mixing_bowl/mix/lock run return run data modify entity @s item.components.'minecraft:custom_data'.spiced.mix_callback set value 'spiced:recipes/mixing_bowl/cooking_oil'