#------------------------------------------------------------------------------------
# HEY! This file is code from Crop & Kettle by Creature Comforts!
# We have been given permission to utilize it for use at smithed summit by MaybeJake.
# We do NOT claim any legal right or creative license to this file.
#------------------------------------------------------------------------------------

execute \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:sugar"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:red_dye"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:white_dye"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/candy_cane

execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"stock"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"butter"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:wheat"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/demi-glace

execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"stock"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"butter"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:potato"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/fondant_potatoes

execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"dough"}}}}}] \
        if function spiced:cooking_pot/crafting/generic/mushroom if score $mushroom_count spiced.dummy matches 1 \
        if function spiced:cooking_pot/crafting/generic/beef if score $beef_count spiced.dummy matches 1 \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/beef_wellington

execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{"straw_hat":true}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"tortilla_chips"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"cheese"}}}}}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/tortilla_sombrero

execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"dough"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:sugar"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:paper"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/fortune_cookie/main

# code below is generated by beet