#------------------------------------------------------------------------------------
# HEY! This file is code from Crop & Kettle by Creature Comforts!
# We have been given permission to utilize it for use at smithed summit by MaybeJake.
# We do NOT claim any legal right or creative license to this file.
#------------------------------------------------------------------------------------

execute \
        if function spiced:cooking_pot/crafting/generic/dye if score $dye_count spiced.dummy matches 1 \
        if function spiced:cooking_pot/crafting/generic/milk if score $milk_count spiced.dummy matches 1 \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"dough"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:sugar"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/festive_cookie/main

execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"dough"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:tnt"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:apple"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:sugar"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/psys_explosive_apple_pie

# code below is generated by beet