execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"dough"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:sugar"}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"ginger"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"cinnamon"}}}}}] \
        if function spiced:cooking_pot/crafting/generic/milk if score $milk_count spiced.dummy matches 1 \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/gingerbread

execute \
        if function spiced:cooking_pot/crafting/generic/egg if score $egg_count spiced.dummy matches 1 \
        if function spiced:cooking_pot/crafting/generic/water if score $water_count spiced.dummy matches 1 \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:sugar"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:wheat"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:glowstone"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/promised_cupcake

execute \
        if function spiced:cooking_pot/crafting/generic/chicken if score $chicken_count spiced.dummy matches 1 \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:shulker_shell"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:bread"}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"lettuce"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"tomato"}}}}}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/jakes_uplifting_lunch

execute \
        if function spiced:cooking_pot/crafting/generic/meat if score $meat_count spiced.dummy matches 3 \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:spider_eye"}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:bone"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/mystery_meat

execute \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"beef_wellington"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"fondant_potatoes"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"vegetable_puree"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"demi-glace"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"fine_wine"}}}}}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/foodie_feast

execute \
        if function spiced:cooking_pot/crafting/generic/pork if score $pork_count spiced.dummy matches 1 \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"tomato"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"noodles"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{components:{"minecraft:custom_data":{spiced:{ingredient:{type:"cheese"}}}}}] \
        if data storage spiced:temp cooking_pot.Items[{id:"minecraft:blaze_powder"}] \
        if function spiced:cooking_pot/crafting/lock \
        run return run function spiced:recipes/cooking_pot/crs_fireball_pasta

# code below is generated by beet